### ISSUE TITLE
bug bitgesell-bridge

### ISSUE THREAD

**Issue by maicontavora** [BitgesellOfficial/bitgesell#69]
hello who can fix this bug. I need to get my coins back no answer so far
[BitgesellOfficial
/
wbgl-bridge
](https://github.com/BitgesellOfficial/wbgl-bridge/issues/5)

**Comment by ayushkumar63123** [comment]
I am willing to do anything possible for the welfare of this organization I am definitely willing to look into this problem

**Comment by ayushkumar63123** [comment]
Please elaborate the issue I will do my best ASAP

**Comment by ayushkumar63123** [comment]
I looked into your problem statement and forwarded the issue to BGL telegram group. As soon as they respond to my queries regarding this problem I will immediately start the technical process or anything required to solve this monetary issue of yours
Thanks

**Comment by maicontavora** [comment]
Ok thank

Em dom., 28 de nov. de 2021 04:06, ayushkumar63123 ***@***.***>
escreveu:

**Comment by ayushkumar63123** [comment]
I also have a request can you please review my issue that I have solved and
tell whether it would qualify bgl pr bounty standards?

**Comment by ayushkumar63123** [comment]
I have recently solved few bugs but haven't got an effective reply

**Comment by maicontavora** [comment]
I'm disappointed waiting for a bridge solution unfortunately, I have suspended my trading in this currency and advised other investors and exchanges not to trust the bridge

**Comment by maicontavora** [comment]
sorted out
