### ISSUE TITLE
Last error I suppose

### ISSUE THREAD

**Issue by ayushkumar63123** [BitgesellOfficial/bitgesell#73]
I solved all the previous errors and this may be the last error I suppose
import file mismatch:
imported module 'test_runner' has this __file__ attribute:
  /home/runner/work/bitgesell/bitgesell/test/functional/test_runner.py
which is not the same as the test file we want to collect:
  /home/runner/work/bitgesell/bitgesell/test/fuzz/test_runner.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=============================== warnings summary ===============================
test/functional/test_runner.py:487
  /home/runner/work/bitgesell/bitgesell/test/functional/test_runner.py:487: PytestCollectionWarning: cannot collect test class 'TestHandler' because it has a __init__ constructor (from: test/functional/test_runner.py)
    class TestHandler:

test/functional/test_runner.py:574
  /home/runner/work/bitgesell/bitgesell/test/functional/test_runner.py:574: PytestCollectionWarning: cannot collect test class 'TestResult' because it has a __init__ constructor (from: test/functional/test_runner.py)
    class TestResult():

test/functional/test_framework/test_framework.py:38
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_framework.py:38: PytestCollectionWarning: cannot collect test class 'TestStatus' because it has a __new__ constructor (from: test/functional/test_framework/test_framework.py)
    class TestStatus(Enum):

test/functional/test_framework/test_node.py:49
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_node.py:49: PytestCollectionWarning: cannot collect test class 'TestNode' because it has a __init__ constructor (from: test/functional/test_framework/test_framework.py)
    class TestNode():

test/functional/test_framework/test_node.py:49
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_node.py:49: PytestCollectionWarning: cannot collect test class 'TestNode' because it has a __init__ constructor (from: test/functional/test_framework/test_node.py)
    class TestNode():

test/functional/test_framework/test_node.py:478
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_node.py:478: PytestCollectionWarning: cannot collect test class 'TestNodeCLIAttr' because it has a __init__ constructor (from: test/functional/test_framework/test_node.py)
    class TestNodeCLIAttr:

test/functional/test_framework/test_node.py:497
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_node.py:497: PytestCollectionWarning: cannot collect test class 'TestNodeCLI' because it has a __init__ constructor (from: test/functional/test_framework/test_node.py)
    class TestNodeCLI():

test/functional/test_framework/test_shell.py:8
  /home/runner/work/bitgesell/bitgesell/test/functional/test_framework/test_shell.py:8: PytestCollectionWarning: cannot collect test class 'TestShell' because it has a __new__ constructor (from: test/functional/test_framework/test_shell.py)
    class TestShell:

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR test/fuzz/test_runner.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================== 8 warnings, 1 error in 11.28s =========================
Error: Process completed with exit code 2.
Please solve this yourself and reward me if possible. I have done much work.

**Comment by ayushkumar63123** [comment]
And please review fast. I have been working and waiting too long.

**Comment by ayushkumar63123** [comment]
And fork my repository for already solved errors and fresh code having no errors but only this last error.
https://github.com/ayushkumar63123/bitgesell

**Comment by ayushkumar63123** [comment]
@janus Please tell whether this work will be rewarded?

**Comment by janus** [comment]
> @janus Please tell whether this work will be rewarded?

Make your code to work

**Comment by ayushkumar63123** [comment]
You are misunderstood. It's not my code. It's error in your project code. I
found it while testing and solved three out of four errors. Check it
thoroughly. I have not written the erroneous code.

**Comment by ayushkumar63123** [comment]
I have found three errors in your code. I have not written my own erroneous code.

**Comment by ayushkumar63123** [comment]
I tested your project with pytest and successfully found four bugs.

**Comment by ayushkumar63123** [comment]
This error, as written on forum https://stackoverflow.com/questions/21430900/py-test-skips-test-class-if-constructor-is-defined is not a syntax problem. The skipping of test files having __init__ constructor is as expected. When testing with flake8, the build was successful. I am now deleting pytest framework from the project. The syntax of the program is now solved by m
![Screenshot (344)](https://user-images.githubusercontent.com/86553805/143576043-b145522e-bdd3-4d6e-b5b3-06951e510d93.png)
e.

**Comment by ayushkumar63123** [comment]
Please reward if possible since I solved your program's three bugs.

**Comment by ayushkumar63123** [comment]
@janus Although the errors were not mine, I solved them to bring value to your organization. So please proceed as soon as possible. I am a part-time bug bounty hunter. I had seen the bounty on gitcoin.

**Comment by ayushkumar63123** [comment]
I am waiting for a fortunate reply from your side.

**Comment by ayushkumar63123** [comment]
@wu-emma please take a look at my service as a part of bgl pr bounty hunt on gitcoin

**Comment by ayushkumar63123** [comment]
> > @janus Please tell whether this work will be rewarded?
> 
> Make your code to work

Please reply

**Comment by ayushkumar63123** [comment]
The issue doesn't persist anymore I have tested it and it's correct please tell whether I will gain profit for job

**Comment by ayushkumar63123** [comment]
For proof I have sent screenshot of successful build above

**Comment by ayushkumar63123** [comment]
@janus If my work gets checked soon, I will proceed with further development and bug finding for bitgesell So please check it soon

**Comment by ayushkumar63123** [comment]
Are you there?

**Comment by ayushkumar63123** [comment]
Please do not ignore. I have worked hard on this.

**Comment by ayushkumar63123** [comment]
> e to work

My code works. Your syntax errors solved. Why still not reward?
