### ISSUE TITLE
https://github.com/BGL-core/gui points to A `404` page

### ISSUE THREAD

**Issue by naftalimurgor** [BitgesellOfficial/bitgesell#82]
hello @wu-emma :wave: 

https://github.com/BGL-core/gui link points to a `404` page. Any pointers are highly welcome. Highly interested in working on the GUI portion.
This relates to the Gitcoin issue here: https://gitcoin.co/issue/29031
Thanks

**Comment by janus** [comment]
> hello @wu-emma wave
> 
> https://github.com/BGL-core/gui link points to a `404` page. Any pointers are highly welcome. Highly interested in working on the GUI portion. This relates to the Gitcoin issue here: https://gitcoin.co/issue/29031 Thanks
@naftalimurgor 
Please use this link, https://github.com/BitgesellOfficial/.

**Comment by naftalimurgor** [comment]
@janus Okay thank you

**Comment by naftalimurgor** [comment]
@janus Thanks for the pointer but it seems ai can't find the GUI repository is the GUI repository within the Core repo?

**Comment by janus** [comment]
> @janus Thanks for the pointer but it seems ai can't find the GUI repository is the GUI repository within the Core repo?

Did you check qt folder?

**Comment by naftalimurgor** [comment]
@janus 
I checked and found `qt` folder,
Thank you
